### PR TITLE
Kazantsev Evgeny Lab3 v1

### PR DESCRIPTION
**Pull request by neotouch1**
Optimizes sequences of multiply and add instructions on the X86 architecture

### CODE REVIEW

**Comment by aobolensk** [comment]
Is this patch relevant? Or shall we close it?

**Comment by neotouch1** [comment]
> Is this patch relevant? Or shall we close it?

Yes, relevant.

**Comment by neotouch1** [comment]
@aobolensk 
Я ч

**Comment by neotouch1** [comment]
@aobolensk 
I'm confused. The lab is in the main branch and in a pull request.

**Comment by m-ly4** [comment]
> @aobolensk I'm confused. The lab is in the main branch and in a pull request.

You've already passed it earlier (https://github.com/NN-complr-tech/llvm-nnsu-2024/pull/134).
If it was you, of course.

**Comment by aobolensk** [comment]
It looks like it should be closed

**Pull request closed without merging**
